apiVersion: v1
description: Microservice Helm Chart Contain echo-server and hello-world applications
name: Microservice
version: 1.0.0
appVersion: 1.0.0
# home: aaffb5d9be08944338f53d09c17ad8b7-1713823100.ap-southeast-1.elb.amazonaws.com
